name: Node.js Package

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run:
        command: |
          rm package-lock.json
          sed -i -e 's|"version": "1.0.0"|"version": "'"$TAG"'"|g' ./package.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
